Document: gnome-inm-forecast
Title: Debian gnome-inm-forecast Manual
Author: <insert document author here>
Abstract: This manual describes what gnome-inm-forecast is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnome-inm-forecast/gnome-inm-forecast.sgml.gz

Format: postscript
Files: /usr/share/doc/gnome-inm-forecast/gnome-inm-forecast.ps.gz

Format: text
Files: /usr/share/doc/gnome-inm-forecast/gnome-inm-forecast.text.gz

Format: HTML
Index: /usr/share/doc/gnome-inm-forecast/html/index.html
Files: /usr/share/doc/gnome-inm-forecast/html/*.html

  
